# This file was generated by GoReleaser. DO NOT EDIT.
cask "comai" do
  name "comai"
  desc "Use AI to write your git commit messages and more"
  homepage "https://github.com/JulienQNN/comai"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "comai"
  bash_completion "completions/comai.bash"
  zsh_completion "completions/comai.zsh"
  fish_completion "completions/comai.fish"

  on_macos do
    on_intel do
      url "https://github.com/JulienQNN/comai/releases/download/v#{version}/comai_#{version}_darwin_amd64.tar.gz"
      sha256 "fba441b4775069b5de38ea61e05b0bf4a2c052a2deb2977fbd76e03225ff5ff4"
    end
    on_arm do
      url "https://github.com/JulienQNN/comai/releases/download/v#{version}/comai_#{version}_darwin_arm64.tar.gz"
      sha256 "d4dc7e999d201ed7dc1373d83c36e67f443a8a115cc990eb856267c48ee43d81"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/JulienQNN/comai/releases/download/v#{version}/comai_#{version}_linux_amd64.tar.gz"
      sha256 "d637d80aedd85201e0eef1fa29499e007308dcee4aad51735968b13db2fe4411"
    end
    on_arm do
      url "https://github.com/JulienQNN/comai/releases/download/v#{version}/comai_#{version}_linux_arm64.tar.gz"
      sha256 "c4d10516cbe32b604d8c4aa5e0ed9039bc4c921e3284ee359c04462de93d33ca"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/comai"]
    end
  end

  # No zap stanza required
end
