# This file was generated by GoReleaser. DO NOT EDIT.
cask "comai" do
  name "comai"
  desc "Use AI to write your git commit messages and more"
  homepage "https://github.com/JulienQNN/comai"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "comai"
  bash_completion "completions/comai.bash"
  zsh_completion "completions/comai.zsh"
  fish_completion "completions/comai.fish"

  on_macos do
    on_intel do
      url "https://github.com/JulienQNN/comai/releases/download/v#{version}/comai_#{version}_darwin_amd64.tar.gz"
      sha256 "ff46121e7c11f40a1741a0e836424aa3c602028d720688c9212104f80fafa885"
    end
    on_arm do
      url "https://github.com/JulienQNN/comai/releases/download/v#{version}/comai_#{version}_darwin_arm64.tar.gz"
      sha256 "f782cf34bbd63e36122814984eb37d1016048883a874ceb6db7f86156175d38b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/JulienQNN/comai/releases/download/v#{version}/comai_#{version}_linux_amd64.tar.gz"
      sha256 "429f2c275f321c524605c4ee2ae43133fd802ee157b493055cedf366390becbb"
    end
    on_arm do
      url "https://github.com/JulienQNN/comai/releases/download/v#{version}/comai_#{version}_linux_arm64.tar.gz"
      sha256 "f0661d96776d512bf1a35674b1812fd96a6299f4042d5412f2a2906e4dbba7f5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/comai"]
    end
  end

  # No zap stanza required
end
